services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: autogen-app
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: " "
      ENV_VAR: "value"
    restart: unless-stopped
